package com.dpsg.cyberx;

import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

// NOTE: This class sets up the main dashboard and handles navigation to all 4 modules.

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Set the content view to the XML layout (activity_main.xml)
        setContentView(R.layout.activity_main);

        // 1. Initialize and configure the Dashboard Cards
        setupDashboardCards();
    }

    /**
     * Finds the included card views and sets their specific content and click listeners.
     */
    private void setupDashboardCards() {
        // Find all the included layout views by their IDs in activity_main.xml
        View cardPermissions = findViewById(R.id.card_permissions);
        View cardRealTime = findViewById(R.id.card_realtime);
        View cardReports = findViewById(R.id.card_reports);
        View cardAlerts = findViewById(R.id.card_alerts);

        // --- Helper function to simplify card setup ---
        // 1. App Permission Manager
        setupCard(
                cardPermissions,
                "App Permission Manager",
                "View, audit, and revoke permissions for all installed apps.",
                "Audit Apps",
                R.color.design_default_color_primary,
                this::onPermissionsClick
        );

        // 2. Real-Time Monitoring
        setupCard(
                cardRealTime,
                "Real-Time Monitoring",
                "Monitor live usage of Camera, Microphone, and Location.",
                "View Live Feed",
                R.color.purple_500, // Assuming purple_500 is defined in colors.xml
                this::onRealTimeClick
        );

        // 3. Privacy Reports (Phase 5)
        setupCard(
                cardReports,
                "Privacy Reports",
                "Review system health, running processes, CPU, and Memory usage.",
                "View Reports",
                R.color.design_default_color_secondary, // Green
                this::onReportsClick
        );

        // 4. AI Behavioral Alerts (Phase 6)
        setupCard(
                cardAlerts,
                "AI Behavioral Alerts",
                "Review security alerts generated by usage and resource anomalies.",
                "Review Alerts",
                R.color.design_default_color_error, // Red
                this::onAlertsClick
        );
    }

    /**
     * Utility method to set text and click listeners for the generic card template.
     */
    private void setupCard(View cardView, String title, String description, String buttonText, int colorResId, View.OnClickListener listener) {
        // Set content
        TextView titleText = cardView.findViewById(R.id.card_title);
        TextView descText = cardView.findViewById(R.id.card_description);
        Button actionButton = cardView.findViewById(R.id.card_button);

        titleText.setText(title);
        descText.setText(description);
        actionButton.setText(buttonText);

        // Set button color
        actionButton.setBackgroundTintList(getResources().getColorStateList(colorResId, getTheme()));

        // Set click listener
        actionButton.setOnClickListener(listener);
    }

    // --- Click Handlers (Navigation) ---

    private void onPermissionsClick(View view) {
        Intent intent = new Intent(MainActivity.this, AppPermissionsActivity.class);
        startActivity(intent);
    }

    private void onRealTimeClick(View view) {
        Intent intent = new Intent(MainActivity.this, RealTimeMonitorActivity.class);
        startActivity(intent);
    }

    private void onReportsClick(View view) {
        Intent intent = new Intent(MainActivity.this, ReportsActivity.class);
        startActivity(intent);
    }

    private void onAlertsClick(View view) {
        // Final Logic for Phase 6
        Intent intent = new Intent(MainActivity.this, AlertsActivity.class);
        startActivity(intent);
    }
}